### PR TITLE
Modern theme for waterfall progress indicator

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**
https://blackbaud.invisionapp.com/console/share/UG1N3XTCC7/547181356

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme)

**Review by Blackbaud-SteveBrush — DISMISSED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/skyux-progress-indicator?_sp.spa=pr-modern-theme)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme](https://developer.blackbaud.com/progress-indicator?_sp.spa=pr-modern-theme)

**Review by Blackbaud-AdamFunderburk — APPROVED** [review]

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
